### ISSUE TITLE
TAB key not working in Firefox

### ISSUE THREAD

**Issue by rePhat** [jessegreathouse/TinyEditor#11]
Tab key doesn't work properly in Firefox 42.
USER-AGENT: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0`

When using Chrome, TinyEditor adds `<span class="Apple-tab-span" style="white-space:pre">`.
I've tried to view TinyEditor source code in order to understand what is happening, however I could'nt find `.Apple-tab-span` anywhere in the source code. 

How does tab key work in chrome?
Is there any way I can handle keys in order to fix this issue?

Thanks for your awesome work!

**Comment by jessegreathouse** [comment]
This editor is deprecated. If you would like to submit a PR with any changes you see fit, I would be amenable to merging additions, however this code is over 10 years old and really should not be used in new development. It only remains on github to support legacy applications.
