### ISSUE TITLE
Make it browser independant.

### ISSUE THREAD

**Issue by abdelouahabb** [jessegreathouse/TinyEditor#13]
Hi,
There is a problem while generating something using Chrome, is that it generates:

`style="font-size: -webkit-xxx-large;"` which doesent work of course with Firefox, what makes the result dependent only with Chromium browsers.

**Comment by abdelouahabb** [comment]
Found a temporary trick, while generating the markup, use this:

`editor.t.value.split("-webkit-xxx-large").join("4em")`

**Comment by jessegreathouse** [comment]
This is a great suggestion, however, this editor is deprecated. If you would like to submit a PR with any changes you see fit, I would be amenable to merging additions, however this code is over 10 years old and really should not be used in new development. It only remains on github to support legacy applications.
