### ISSUE TITLE
Add Ability To Focus if Field Empty

### ISSUE THREAD

**Issue by volomike** [jessegreathouse/TinyEditor#14]
If the field is empty, it would be great to set focus on it so that once visible, I can just start typing.

**Comment by volomike** [comment]
I found a way. Where you add the BODY tag, add this attribute:

```
 onload="this.focus();"
```

Even cooler would be to make this an option one can set on or off.

**Comment by jessegreathouse** [comment]
This is a great suggestion, however, this editor is deprecated. If you would like to submit a PR with any changes you see fit, I would be amenable to merging additions, however this code is over 10 years old and really should not be used in new development.
