### ISSUE TITLE
website is hacked

### ISSUE THREAD

**Issue by dawidcieszynski** [jessegreathouse/TinyEditor#7]
http://www.scriptiny.com/2010/02/javascript-wysiwyg-editor/

Hacked by Abdellah Elmaghribi
Hahahaha Web Devolopper :v

**Comment by jessegreathouse** [comment]
well that's unfortunate...

**Comment by kirvedx** [comment]
lol...how does one hack a website for so long?

I mean I get that someone could potentially hack a system...but the original owner doesn't reload the server and start again? Or perhaps call his hosting provider and have them clean the system (I assume the site's not on a shared host and hacked...they usually shut those sites down until you clean them...)

No issues here...just took a browse through this and wanted to comment on it :P

**Comment by jessegreathouse** [comment]
@rikkotec I have no idea. I don't know anything about their site. _shrugs_. This really isn't an "issue" so I'm closing it.
