### ISSUE TITLE
Allow raw input via style

### ISSUE THREAD

**Issue by kirvedx** [jessegreathouse/TinyEditor#8]
Could we add the ability to select a style that will cause TinyEditor to wrap subsequent input with `<pre>` tags and allow raw characters within; rather than always wrapping everything with html entities (i.e. newlines, < instead of &lt;, etc)?

If you're still active on this project I wouldn't mind tinkering with it and submitting a pull request if successful.

Let me know :)

**Comment by jessegreathouse** [comment]
@rikkotec Submit a PR and I will merge it. I don't work on this project so I wouldn't be able to help other than merging a PR.
